defaults: &defaults
  s3_bucket: "iqe-sgo-development"
  s3_access_key_id: "AKIAJPZA2FRKBQBZ24MQ"
  s3_secret_access_key: "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"
  smtp:
    username: "AKIAIUMLQOVK4TWLG6PA"
    password: "AscBkv/hrps24dwALz0jXhoxKkJPy9hejyChYFFXNyey"
  notification_recipients:
    sgo_approval: "forrest@yellowdoes.com"
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  s3_bucket: "iqe-sgo-production"
  notification_recipients:
    sgo_approval: "forrest@yellowdoes.com"