defaults: &defaults
  s3_bucket: "sgo-development"
  s3_access_key_id: "AKIAJZ3SHIAREQAZYJMA"
  s3_secret_access_key: "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"
development:
  <<: *defaults
test:
  <<: *defaults
production:
  <<: *defaults
  s3_bucket: "sgo-production"